version: "3.8"
services:
  sveltekit-js:
    image: sveltekit-js-dev
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5173"
    volumes:
      - ./src:/var/www/html/src
      - ./static:/var/www/html/static
      - ./vite.config.js:/var/www/html/vite.config.js
      - ./jsconfig.json:/var/www/html/jsconfig.json
      - ./svelte.config.js:/var/www/html/svelte.config.js
    command: npm run dev
    environment:
      - PORT=5173
      - HOST=0.0.0.0